name: Merge Upstream to Downstream Development

# Controls when the action will run.
on:
  schedule:
    - cron: "0 0 * * *"
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow starts with a merge from origin to master
  origin2master:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!
      - name: Set upstream
        run: git remote add upstream https://github.com/North-Seattle-College/ad440-winter2021-tuesday-repo.git
      - name: Set email
        run: git config --local user.email "action@github.com"
      - name: Set username
        run: git config --local user.name "GitHub Action"
      - name: Fetch upstream
        run: git fetch upstream
      - name: Merge upstream
        run: git merge -X theirs upstream/development --allow-unrelated-histories
      - name: Push changes 
        run: git push 